name: Upload to an AWS S3 bucket
description: 'Uploads a directory to an AWS S3 bucket'
author: 'Andrew McLachlan'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  aws_access_key:
    description: 'AWS access key'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_region:
    description: 'AWS S3 region'
    required: true
  aws_s3_bucket:
    description: 'AWS S3 bucket'
    required: true
  source_dir:
    required: true
    description: 'source directory to upload'
  destination_dir:
    required: false
    default: /
    description: 'destination directory for the upload'
outputs:
  object_key:
    description: 'object key'
  object_tags:
    description: 'object tags'
runs:
  using: 'node20'
  main: 'dist/index.js'
